// <auto-generated/>
#pragma warning disable CS0618
using LGDXRobotCloud.UI.Client.Automation.TriggerRetries.Triggers.Item.Retry;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LGDXRobotCloud.UI.Client.Automation.TriggerRetries.Triggers.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \Automation\TriggerRetries\Triggers\{triggerId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTriggerItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Retry property</summary>
        public global::LGDXRobotCloud.UI.Client.Automation.TriggerRetries.Triggers.Item.Retry.RetryRequestBuilder Retry
        {
            get => new global::LGDXRobotCloud.UI.Client.Automation.TriggerRetries.Triggers.Item.Retry.RetryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Automation.TriggerRetries.Triggers.Item.WithTriggerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTriggerItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Automation/TriggerRetries/Triggers/{triggerId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Automation.TriggerRetries.Triggers.Item.WithTriggerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTriggerItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Automation/TriggerRetries/Triggers/{triggerId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
