// <auto-generated/>
#pragma warning disable CS0618
using LGDXRobotCloud.UI.Client.Automation.AutoTasksNext.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LGDXRobotCloud.UI.Client.Automation.AutoTasksNext
{
    /// <summary>
    /// Builds and executes requests for operations under \Automation\AutoTasksNext
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AutoTasksNextRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the LGDXRobotCloud.UI.Client.Automation.AutoTasksNext.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Automation.AutoTasksNext.Item.AutoTasksNextItemRequestBuilder"/></returns>
        public global::LGDXRobotCloud.UI.Client.Automation.AutoTasksNext.Item.AutoTasksNextItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::LGDXRobotCloud.UI.Client.Automation.AutoTasksNext.Item.AutoTasksNextItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the LGDXRobotCloud.UI.Client.Automation.AutoTasksNext.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Automation.AutoTasksNext.Item.AutoTasksNextItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::LGDXRobotCloud.UI.Client.Automation.AutoTasksNext.Item.AutoTasksNextItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::LGDXRobotCloud.UI.Client.Automation.AutoTasksNext.Item.AutoTasksNextItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Automation.AutoTasksNext.AutoTasksNextRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AutoTasksNextRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Automation/AutoTasksNext", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Automation.AutoTasksNext.AutoTasksNextRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AutoTasksNextRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Automation/AutoTasksNext", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
