// <auto-generated />
using System;
using LGDXRobot2Cloud.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LGDXRobot2Cloud.API.Migrations
{
    [DbContext(typeof(LgdxContext))]
    [Migration("20240329144341_timePrecision")]
    partial class timePrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FlowEndTrigger", b =>
                {
                    b.Property<int>("EndTriggersId")
                        .HasColumnType("int");

                    b.Property<int>("FlowsId")
                        .HasColumnType("int");

                    b.HasKey("EndTriggersId", "FlowsId");

                    b.HasIndex("FlowsId");

                    b.ToTable("FlowEndTrigger");
                });

            modelBuilder.Entity("FlowProgress", b =>
                {
                    b.Property<int>("FlowsId")
                        .HasColumnType("int");

                    b.Property<int>("ProgressesId")
                        .HasColumnType("int");

                    b.HasKey("FlowsId", "ProgressesId");

                    b.HasIndex("ProgressesId");

                    b.ToTable("FlowProgress");
                });

            modelBuilder.Entity("FlowStartTrigger", b =>
                {
                    b.Property<int>("EndTriggersId")
                        .HasColumnType("int");

                    b.Property<int>("FlowsId")
                        .HasColumnType("int");

                    b.HasKey("EndTriggersId", "FlowsId");

                    b.HasIndex("FlowsId");

                    b.ToTable("FlowStartTrigger");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.Property<bool>("isThirdParty")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.ApiKeyLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.HasKey("Id");

                    b.ToTable("ApiKeyLocations");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.Flow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SystemComponentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.HasKey("Id");

                    b.HasIndex("SystemComponentId");

                    b.ToTable("Flows");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("NodesCollectionId")
                        .HasColumnType("int");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.HasKey("Id");

                    b.HasIndex("NodesCollectionId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.NodesCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.HasKey("Id");

                    b.ToTable("NodesCollections");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.Progress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("System")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.HasKey("Id");

                    b.ToTable("Progresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1320),
                            Name = "Waiting",
                            System = true,
                            UpdatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1320)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1330),
                            Name = "Starting",
                            System = true,
                            UpdatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1330)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1330),
                            Name = "Loading",
                            System = true,
                            UpdatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1330)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1330),
                            Name = "Moving",
                            System = true,
                            UpdatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1330)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1330),
                            Name = "Unloading",
                            System = true,
                            UpdatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1330)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1330),
                            Name = "Completing",
                            System = true,
                            UpdatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1330)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1330),
                            Name = "Completed",
                            System = true,
                            UpdatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1330)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1340),
                            Name = "Aborted",
                            System = true,
                            UpdatedAt = new DateTime(2024, 3, 29, 14, 43, 41, 119, DateTimeKind.Utc).AddTicks(1340)
                        });
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.Robot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NodesCollectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.HasKey("Id");

                    b.HasIndex("NodesCollectionId");

                    b.ToTable("Robots");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.RobotTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FlowId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.ToTable("RobotTasks");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.SystemComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SystemComponents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "api"
                        },
                        new
                        {
                            Id = 2,
                            Name = "robot"
                        });
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.Trigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiKeyId")
                        .HasColumnType("int");

                    b.Property<int>("ApiKeyLocationId")
                        .HasColumnType("int");

                    b.Property<string>("ApiKeyName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("ApiKeyLocationId");

                    b.ToTable("Triggers");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.Waypoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime(3)");

                    b.Property<double>("W")
                        .HasColumnType("double");

                    b.Property<double>("X")
                        .HasColumnType("double");

                    b.Property<double>("Y")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Waypoints");
                });

            modelBuilder.Entity("RobotTaskWaypoint", b =>
                {
                    b.Property<int>("RobotTasksId")
                        .HasColumnType("int");

                    b.Property<int>("WaypointsId")
                        .HasColumnType("int");

                    b.HasKey("RobotTasksId", "WaypointsId");

                    b.HasIndex("WaypointsId");

                    b.ToTable("RobotTaskWaypoint");
                });

            modelBuilder.Entity("FlowEndTrigger", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.API.Entities.Trigger", null)
                        .WithMany()
                        .HasForeignKey("EndTriggersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGDXRobot2Cloud.API.Entities.Flow", null)
                        .WithMany()
                        .HasForeignKey("FlowsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowProgress", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.API.Entities.Flow", null)
                        .WithMany()
                        .HasForeignKey("FlowsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGDXRobot2Cloud.API.Entities.Progress", null)
                        .WithMany()
                        .HasForeignKey("ProgressesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowStartTrigger", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.API.Entities.Trigger", null)
                        .WithMany()
                        .HasForeignKey("EndTriggersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGDXRobot2Cloud.API.Entities.Flow", null)
                        .WithMany()
                        .HasForeignKey("FlowsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.Flow", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.API.Entities.SystemComponent", "ProceedCondition")
                        .WithMany()
                        .HasForeignKey("SystemComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProceedCondition");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.Node", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.API.Entities.NodesCollection", null)
                        .WithMany("Nodes")
                        .HasForeignKey("NodesCollectionId");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.Robot", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.API.Entities.NodesCollection", "NodesCollection")
                        .WithMany()
                        .HasForeignKey("NodesCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NodesCollection");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.RobotTask", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.API.Entities.Flow", "Flow")
                        .WithMany()
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flow");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.Trigger", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.API.Entities.ApiKey", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGDXRobot2Cloud.API.Entities.ApiKeyLocation", "ApiKeyLocation")
                        .WithMany()
                        .HasForeignKey("ApiKeyLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");

                    b.Navigation("ApiKeyLocation");
                });

            modelBuilder.Entity("RobotTaskWaypoint", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.API.Entities.RobotTask", null)
                        .WithMany()
                        .HasForeignKey("RobotTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGDXRobot2Cloud.API.Entities.Waypoint", null)
                        .WithMany()
                        .HasForeignKey("WaypointsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LGDXRobot2Cloud.API.Entities.NodesCollection", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
