FROM mcr.microsoft.com/dotnet/sdk:9.0.301@sha256:b768b444028d3c531de90a356836047e48658cd1e26ba07a539a6f1a052a35d9 AS build
WORKDIR /App
COPY . ./
WORKDIR /App/LGDXRobotCloud.Worker
RUN dotnet restore
RUN dotnet publish --property:PublishDir=./out

# Build
FROM mcr.microsoft.com/dotnet/aspnet:9.0.7@sha256:f90174159add063f40041160baf4ead693302a285c12fa74e60154f1d7acbc16
WORKDIR /App
COPY --from=build /App/LGDXRobotCloud.Worker/out .
ENTRYPOINT ["dotnet", "LGDXRobotCloud.Worker.dll"]
