// <auto-generated/>
#pragma warning disable CS0618
using LGDXRobotCloud.UI.Client.Navigation.MapEdit.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LGDXRobotCloud.UI.Client.Navigation.MapEdit
{
    /// <summary>
    /// Builds and executes requests for operations under \Navigation\MapEdit
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MapEditRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the LGDXRobotCloud.UI.Client.Navigation.MapEdit.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Navigation.MapEdit.Item.WithRealmItemRequestBuilder"/></returns>
        public global::LGDXRobotCloud.UI.Client.Navigation.MapEdit.Item.WithRealmItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("realmId", position);
                return new global::LGDXRobotCloud.UI.Client.Navigation.MapEdit.Item.WithRealmItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the LGDXRobotCloud.UI.Client.Navigation.MapEdit.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Navigation.MapEdit.Item.WithRealmItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::LGDXRobotCloud.UI.Client.Navigation.MapEdit.Item.WithRealmItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("realmId", position);
                return new global::LGDXRobotCloud.UI.Client.Navigation.MapEdit.Item.WithRealmItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Navigation.MapEdit.MapEditRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MapEditRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Navigation/MapEdit", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Navigation.MapEdit.MapEditRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MapEditRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Navigation/MapEdit", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
