// <auto-generated/>
#pragma warning disable CS0618
using LGDXRobot2Cloud.UI.Client.Identity.Auth;
using LGDXRobot2Cloud.UI.Client.Identity.User;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LGDXRobot2Cloud.UI.Client.Identity
{
    /// <summary>
    /// Builds and executes requests for operations under \Identity
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IdentityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Auth property</summary>
        public global::LGDXRobot2Cloud.UI.Client.Identity.Auth.AuthRequestBuilder Auth
        {
            get => new global::LGDXRobot2Cloud.UI.Client.Identity.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The User property</summary>
        public global::LGDXRobot2Cloud.UI.Client.Identity.User.UserRequestBuilder User
        {
            get => new global::LGDXRobot2Cloud.UI.Client.Identity.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobot2Cloud.UI.Client.Identity.IdentityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdentityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Identity", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobot2Cloud.UI.Client.Identity.IdentityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdentityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Identity", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
