// <auto-generated />
using System;
using LGDXRobot2Cloud.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LGDXRobot2Cloud.Data.Migrations
{
    [DbContext(typeof(LgdxContext))]
    [Migration("20250210190957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsThirdParty")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Administration.ApiKeys");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.AutoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AssignedRobotId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentProgressId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentProgressOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("FlowId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NextToken")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RealmId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedRobotId");

                    b.HasIndex("CurrentProgressId");

                    b.HasIndex("FlowId");

                    b.HasIndex("RealmId", "AssignedRobotId");

                    b.ToTable("Automation.AutoTasks");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.AutoTaskDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutoTaskId")
                        .HasColumnType("integer");

                    b.Property<double?>("CustomRotation")
                        .HasColumnType("double precision");

                    b.Property<double?>("CustomX")
                        .HasColumnType("double precision");

                    b.Property<double?>("CustomY")
                        .HasColumnType("double precision");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("WaypointId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutoTaskId");

                    b.HasIndex("Order");

                    b.HasIndex("WaypointId");

                    b.ToTable("Automation.AutoTaskDetails");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.Flow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Automation.Flows");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.FlowDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutoTaskNextControllerId")
                        .HasColumnType("integer");

                    b.Property<int>("FlowId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressId")
                        .HasColumnType("integer");

                    b.Property<int?>("TriggerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.HasIndex("Order");

                    b.HasIndex("ProgressId");

                    b.HasIndex("TriggerId");

                    b.ToTable("Automation.FlowDetails");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.LgdxRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.LgdxUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.Progress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Reserved")
                        .HasColumnType("boolean");

                    b.Property<bool>("System")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Automation.Progresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Template",
                            Reserved = true,
                            System = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Waiting",
                            Reserved = true,
                            System = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Completed",
                            Reserved = true,
                            System = true
                        },
                        new
                        {
                            Id = 4,
                            Name = "Aborted",
                            Reserved = true,
                            System = true
                        },
                        new
                        {
                            Id = 5,
                            Name = "Starting",
                            Reserved = false,
                            System = true
                        },
                        new
                        {
                            Id = 6,
                            Name = "Loading",
                            Reserved = false,
                            System = true
                        },
                        new
                        {
                            Id = 7,
                            Name = "PreMoving",
                            Reserved = false,
                            System = true
                        },
                        new
                        {
                            Id = 8,
                            Name = "Moving",
                            Reserved = false,
                            System = true
                        },
                        new
                        {
                            Id = 9,
                            Name = "Unloading",
                            Reserved = false,
                            System = true
                        },
                        new
                        {
                            Id = 10,
                            Name = "Completing",
                            Reserved = false,
                            System = true
                        },
                        new
                        {
                            Id = 99,
                            Name = "Reserved",
                            Reserved = true,
                            System = true
                        });
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.Realm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("OriginRotation")
                        .HasColumnType("double precision");

                    b.Property<double>("OriginX")
                        .HasColumnType("double precision");

                    b.Property<double>("OriginY")
                        .HasColumnType("double precision");

                    b.Property<double>("Resolution")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Navigation.Realms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Please update this realm",
                            Image = new byte[0],
                            Name = "First Realm",
                            OriginRotation = 0.0,
                            OriginX = 0.0,
                            OriginY = 0.0,
                            Resolution = 0.0
                        });
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.Robot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsProtectingHardwareSerialNumber")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRealtimeExchange")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RealmId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RealmId");

                    b.ToTable("Navigation.Robots");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.RobotCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NotAfter")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<DateTime>("NotBefore")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ThumbprintBackup")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("RobotId")
                        .IsUnique();

                    b.ToTable("Navigation.RobotCertificates");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.RobotChassisInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryCount")
                        .HasColumnType("integer");

                    b.Property<double>("BatteryMaxVoltage")
                        .HasColumnType("double precision");

                    b.Property<double>("BatteryMinVoltage")
                        .HasColumnType("double precision");

                    b.Property<double>("ChassisLengthX")
                        .HasColumnType("double precision");

                    b.Property<double>("ChassisLengthY")
                        .HasColumnType("double precision");

                    b.Property<int>("ChassisWheelCount")
                        .HasColumnType("integer");

                    b.Property<double>("ChassisWheelRadius")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uuid");

                    b.Property<int>("RobotTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RobotId")
                        .IsUnique();

                    b.ToTable("Navigation.RobotChassisInfos");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.RobotSystemInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gpu")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Is32Bit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLittleEndian")
                        .HasColumnType("boolean");

                    b.Property<string>("McuSerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Motherboard")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MotherboardSerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RamMiB")
                        .HasColumnType("integer");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RobotId")
                        .IsUnique();

                    b.ToTable("Navigation.RobotSystemInfos");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.Trigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKeyFieldName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ApiKeyId")
                        .HasColumnType("integer");

                    b.Property<int?>("ApiKeyInsertLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<int>("HttpMethodId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("SkipOnFailure")
                        .HasColumnType("boolean");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("ApiKeyInsertLocationId");

                    b.ToTable("Automation.Triggers");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.TriggerRetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutoTaskId")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<int>("TriggerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutoTaskId");

                    b.HasIndex("TriggerId");

                    b.ToTable("Automation.TriggerRetries");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.Waypoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasCharger")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsParking")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RealmId")
                        .HasColumnType("integer");

                    b.Property<double>("Rotation")
                        .HasColumnType("double precision");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RealmId");

                    b.ToTable("Navigation.Waypoints");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.AutoTask", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.Robot", "AssignedRobot")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedRobotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LGDXRobot2Cloud.Data.Entities.Progress", "CurrentProgress")
                        .WithMany()
                        .HasForeignKey("CurrentProgressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LGDXRobot2Cloud.Data.Entities.Flow", "Flow")
                        .WithMany()
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LGDXRobot2Cloud.Data.Entities.Realm", "Realm")
                        .WithMany()
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedRobot");

                    b.Navigation("CurrentProgress");

                    b.Navigation("Flow");

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.AutoTaskDetail", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.AutoTask", "AutoTask")
                        .WithMany("AutoTaskDetails")
                        .HasForeignKey("AutoTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGDXRobot2Cloud.Data.Entities.Waypoint", "Waypoint")
                        .WithMany()
                        .HasForeignKey("WaypointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AutoTask");

                    b.Navigation("Waypoint");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.FlowDetail", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.Flow", "Flow")
                        .WithMany("FlowDetails")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGDXRobot2Cloud.Data.Entities.Progress", "Progress")
                        .WithMany()
                        .HasForeignKey("ProgressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LGDXRobot2Cloud.Data.Entities.Trigger", "Trigger")
                        .WithMany()
                        .HasForeignKey("TriggerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Flow");

                    b.Navigation("Progress");

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.Robot", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.Realm", "Realm")
                        .WithMany()
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.RobotCertificate", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.Robot", "Robot")
                        .WithOne("RobotCertificate")
                        .HasForeignKey("LGDXRobot2Cloud.Data.Entities.RobotCertificate", "RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.RobotChassisInfo", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.Robot", "Robot")
                        .WithOne("RobotChassisInfo")
                        .HasForeignKey("LGDXRobot2Cloud.Data.Entities.RobotChassisInfo", "RobotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.RobotSystemInfo", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.Robot", "Robot")
                        .WithOne("RobotSystemInfo")
                        .HasForeignKey("LGDXRobot2Cloud.Data.Entities.RobotSystemInfo", "RobotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.Trigger", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.ApiKey", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.TriggerRetry", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.AutoTask", "AutoTask")
                        .WithMany()
                        .HasForeignKey("AutoTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGDXRobot2Cloud.Data.Entities.Trigger", "Trigger")
                        .WithMany()
                        .HasForeignKey("TriggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutoTask");

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.Waypoint", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.Realm", "Realm")
                        .WithMany()
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.LgdxRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.LgdxUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.LgdxUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.LgdxRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGDXRobot2Cloud.Data.Entities.LgdxUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LGDXRobot2Cloud.Data.Entities.LgdxUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.AutoTask", b =>
                {
                    b.Navigation("AutoTaskDetails");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.Flow", b =>
                {
                    b.Navigation("FlowDetails");
                });

            modelBuilder.Entity("LGDXRobot2Cloud.Data.Entities.Robot", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("RobotCertificate")
                        .IsRequired();

                    b.Navigation("RobotChassisInfo");

                    b.Navigation("RobotSystemInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
