// <auto-generated/>
#pragma warning disable CS0618
using LGDXRobotCloud.UI.Client.Automation.Progresses.Item;
using LGDXRobotCloud.UI.Client.Automation.Progresses.Search;
using LGDXRobotCloud.UI.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LGDXRobotCloud.UI.Client.Automation.Progresses
{
    /// <summary>
    /// Builds and executes requests for operations under \Automation\Progresses
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProgressesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Search property</summary>
        public global::LGDXRobotCloud.UI.Client.Automation.Progresses.Search.SearchRequestBuilder Search
        {
            get => new global::LGDXRobotCloud.UI.Client.Automation.Progresses.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the LGDXRobotCloud.UI.Client.Automation.Progresses.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Automation.Progresses.Item.ProgressesItemRequestBuilder"/></returns>
        public global::LGDXRobotCloud.UI.Client.Automation.Progresses.Item.ProgressesItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::LGDXRobotCloud.UI.Client.Automation.Progresses.Item.ProgressesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the LGDXRobotCloud.UI.Client.Automation.Progresses.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Automation.Progresses.Item.ProgressesItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::LGDXRobotCloud.UI.Client.Automation.Progresses.Item.ProgressesItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::LGDXRobotCloud.UI.Client.Automation.Progresses.Item.ProgressesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Automation.Progresses.ProgressesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProgressesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Automation/Progresses{?name*,pageNumber*,pageSize*,system*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Automation.Progresses.ProgressesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProgressesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Automation/Progresses{?name*,pageNumber*,pageSize*,system*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::LGDXRobotCloud.UI.Client.Models.ProgressDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::LGDXRobotCloud.UI.Client.Models.ProgressDto>?> GetAsync(Action<RequestConfiguration<global::LGDXRobotCloud.UI.Client.Automation.Progresses.ProgressesRequestBuilder.ProgressesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::LGDXRobotCloud.UI.Client.Models.ProgressDto>> GetAsync(Action<RequestConfiguration<global::LGDXRobotCloud.UI.Client.Automation.Progresses.ProgressesRequestBuilder.ProgressesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::LGDXRobotCloud.UI.Client.Models.ProgressDto>(requestInfo, global::LGDXRobotCloud.UI.Client.Models.ProgressDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Models.ProgressDto"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LGDXRobotCloud.UI.Client.Models.ProgressDto?> PostAsync(global::LGDXRobotCloud.UI.Client.Models.ProgressCreateDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LGDXRobotCloud.UI.Client.Models.ProgressDto> PostAsync(global::LGDXRobotCloud.UI.Client.Models.ProgressCreateDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::LGDXRobotCloud.UI.Client.Models.ProgressDto>(requestInfo, global::LGDXRobotCloud.UI.Client.Models.ProgressDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LGDXRobotCloud.UI.Client.Automation.Progresses.ProgressesRequestBuilder.ProgressesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LGDXRobotCloud.UI.Client.Automation.Progresses.ProgressesRequestBuilder.ProgressesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::LGDXRobotCloud.UI.Client.Models.ProgressCreateDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::LGDXRobotCloud.UI.Client.Models.ProgressCreateDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Automation.Progresses.ProgressesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LGDXRobotCloud.UI.Client.Automation.Progresses.ProgressesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LGDXRobotCloud.UI.Client.Automation.Progresses.ProgressesRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class ProgressesRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
            [QueryParameter("pageNumber")]
            public int? PageNumber { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
            [QueryParameter("system")]
            public bool? System { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProgressesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::LGDXRobotCloud.UI.Client.Automation.Progresses.ProgressesRequestBuilder.ProgressesRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProgressesRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
