FROM mcr.microsoft.com/dotnet/sdk:9.0.307@sha256:1ea5b7f2154cbd1e20a336cb56957dba30a7ce30ef5c1c032a37c42801594713 AS build

#
# Build
#

RUN apt-get update && \
    apt-get install -y --no-install-recommends protobuf-compiler && \
    rm -rf /var/lib/apt/lists/*
ENV PROTOBUF_PROTOC=/usr/bin/protoc
WORKDIR /App
COPY . ./
WORKDIR /App/LGDXRobotCloud.API
RUN dotnet restore
RUN dotnet publish --property:PublishDir=./out

#
# Out
#

FROM mcr.microsoft.com/dotnet/aspnet:9.0.11
WORKDIR /App
COPY --from=build /App/LGDXRobotCloud.API/out .
EXPOSE 5162
EXPOSE 5163
EXPOSE 5164
ENTRYPOINT ["dotnet", "LGDXRobotCloud.API.dll"]
