FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

#
# Build
#

WORKDIR /App
COPY . ./
WORKDIR /App/LGDXRobotCloud.Data
RUN dotnet restore
RUN dotnet publish --property:PublishDir=./out

#
# Out
#

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /App
COPY --from=build /App/LGDXRobotCloud.Data/out .
COPY --from=build /App/LGDXRobotCloud.Data/initaliseData.sh .
RUN chmod +x initaliseData.sh
ENTRYPOINT ["./initaliseData.sh"]