FROM mcr.microsoft.com/dotnet/sdk:9.0.301@sha256:b768b444028d3c531de90a356836047e48658cd1e26ba07a539a6f1a052a35d9 AS build
WORKDIR /App
COPY . ./
WORKDIR /App/LGDXRobotCloud.API
RUN dotnet restore
RUN dotnet publish --property:PublishDir=./out

# Build
FROM mcr.microsoft.com/dotnet/aspnet:9.0.7
WORKDIR /App
COPY --from=build /App/LGDXRobotCloud.API/out .
EXPOSE 5162
EXPOSE 5163
EXPOSE 5164
ENTRYPOINT ["dotnet", "LGDXRobotCloud.API.dll"]
