FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

#
# Build
#

WORKDIR /App
COPY . ./
WORKDIR /App/LGDXRobotCloud.UI
RUN dotnet restore
RUN dotnet tool install -g Microsoft.Web.LibraryManager.Cli
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN libman restore
RUN dotnet publish --property:PublishDir=./out

#
# Out
#

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /App
COPY --from=build /App/LGDXRobotCloud.UI/out .
EXPOSE 5102
EXPOSE 5103
ENTRYPOINT ["dotnet", "LGDXRobotCloud.UI.dll"]
