FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

#
# Build
#

WORKDIR /App
COPY . ./
WORKDIR /App/LGDXRobotCloud.Worker
RUN dotnet restore
RUN dotnet publish --property:PublishDir=./out

#
# Out
#

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /App
COPY --from=build /App/LGDXRobotCloud.Worker/out .
ENTRYPOINT ["dotnet", "LGDXRobotCloud.Worker.dll"]
