FROM mcr.microsoft.com/dotnet/sdk:9.0.307@sha256:1ea5b7f2154cbd1e20a336cb56957dba30a7ce30ef5c1c032a37c42801594713 AS build

#
# Build
#

WORKDIR /App
COPY . ./
WORKDIR /App/LGDXRobotCloud.Data
RUN dotnet restore
RUN dotnet publish --property:PublishDir=./out

#
# Out
#

FROM mcr.microsoft.com/dotnet/aspnet:9.0.11
WORKDIR /App
COPY --from=build /App/LGDXRobotCloud.Data/out .
COPY --from=build /App/LGDXRobotCloud.Data/initaliseData.sh .
RUN chmod +x initaliseData.sh
ENTRYPOINT ["./initaliseData.sh"]