// <auto-generated/>
#pragma warning disable CS0618
using LGDXRobotCloud.UI.Client.Identity.User.TwoFA.Disable;
using LGDXRobotCloud.UI.Client.Identity.User.TwoFA.Enable;
using LGDXRobotCloud.UI.Client.Identity.User.TwoFA.Initiate;
using LGDXRobotCloud.UI.Client.Identity.User.TwoFA.Reset;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LGDXRobotCloud.UI.Client.Identity.User.TwoFA
{
    /// <summary>
    /// Builds and executes requests for operations under \Identity\User\2FA
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TwoFARequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Disable property</summary>
        public global::LGDXRobotCloud.UI.Client.Identity.User.TwoFA.Disable.DisableRequestBuilder Disable
        {
            get => new global::LGDXRobotCloud.UI.Client.Identity.User.TwoFA.Disable.DisableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Enable property</summary>
        public global::LGDXRobotCloud.UI.Client.Identity.User.TwoFA.Enable.EnableRequestBuilder Enable
        {
            get => new global::LGDXRobotCloud.UI.Client.Identity.User.TwoFA.Enable.EnableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Initiate property</summary>
        public global::LGDXRobotCloud.UI.Client.Identity.User.TwoFA.Initiate.InitiateRequestBuilder Initiate
        {
            get => new global::LGDXRobotCloud.UI.Client.Identity.User.TwoFA.Initiate.InitiateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Reset property</summary>
        public global::LGDXRobotCloud.UI.Client.Identity.User.TwoFA.Reset.ResetRequestBuilder Reset
        {
            get => new global::LGDXRobotCloud.UI.Client.Identity.User.TwoFA.Reset.ResetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Identity.User.TwoFA.TwoFARequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TwoFARequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Identity/User/2FA", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Identity.User.TwoFA.TwoFARequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TwoFARequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Identity/User/2FA", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
