// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobot2Cloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AutoTaskListDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The assignedRobot property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobot2Cloud.UI.Client.Models.RobotSearchDto? AssignedRobot { get; set; }
#nullable restore
#else
        public global::LGDXRobot2Cloud.UI.Client.Models.RobotSearchDto AssignedRobot { get; set; }
#endif
        /// <summary>The currentProgress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobot2Cloud.UI.Client.Models.ProgressSearchDto? CurrentProgress { get; set; }
#nullable restore
#else
        public global::LGDXRobot2Cloud.UI.Client.Models.ProgressSearchDto CurrentProgress { get; set; }
#endif
        /// <summary>The flow property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobot2Cloud.UI.Client.Models.FlowSearchDto? Flow { get; set; }
#nullable restore
#else
        public global::LGDXRobot2Cloud.UI.Client.Models.FlowSearchDto Flow { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The priority property</summary>
        public int? Priority { get; set; }
        /// <summary>The realm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobot2Cloud.UI.Client.Models.RealmSearchDto? Realm { get; set; }
#nullable restore
#else
        public global::LGDXRobot2Cloud.UI.Client.Models.RealmSearchDto Realm { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobot2Cloud.UI.Client.Models.AutoTaskListDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobot2Cloud.UI.Client.Models.AutoTaskListDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobot2Cloud.UI.Client.Models.AutoTaskListDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignedRobot", n => { AssignedRobot = n.GetObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.RobotSearchDto>(global::LGDXRobot2Cloud.UI.Client.Models.RobotSearchDto.CreateFromDiscriminatorValue); } },
                { "currentProgress", n => { CurrentProgress = n.GetObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.ProgressSearchDto>(global::LGDXRobot2Cloud.UI.Client.Models.ProgressSearchDto.CreateFromDiscriminatorValue); } },
                { "flow", n => { Flow = n.GetObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.FlowSearchDto>(global::LGDXRobot2Cloud.UI.Client.Models.FlowSearchDto.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "realm", n => { Realm = n.GetObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.RealmSearchDto>(global::LGDXRobot2Cloud.UI.Client.Models.RealmSearchDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.RobotSearchDto>("assignedRobot", AssignedRobot);
            writer.WriteObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.ProgressSearchDto>("currentProgress", CurrentProgress);
            writer.WriteObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.FlowSearchDto>("flow", Flow);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("priority", Priority);
            writer.WriteObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.RealmSearchDto>("realm", Realm);
        }
    }
}
#pragma warning restore CS0618
