// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobot2Cloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RobotCertificateDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The notAfter property</summary>
        public DateTimeOffset? NotAfter { get; set; }
        /// <summary>The notBefore property</summary>
        public DateTimeOffset? NotBefore { get; set; }
        /// <summary>The robot property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobot2Cloud.UI.Client.Models.RobotSearchDto? Robot { get; set; }
#nullable restore
#else
        public global::LGDXRobot2Cloud.UI.Client.Models.RobotSearchDto Robot { get; set; }
#endif
        /// <summary>The thumbprint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Thumbprint { get; set; }
#nullable restore
#else
        public string Thumbprint { get; set; }
#endif
        /// <summary>The thumbprintBackup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThumbprintBackup { get; set; }
#nullable restore
#else
        public string ThumbprintBackup { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobot2Cloud.UI.Client.Models.RobotCertificateDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobot2Cloud.UI.Client.Models.RobotCertificateDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobot2Cloud.UI.Client.Models.RobotCertificateDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetGuidValue(); } },
                { "notAfter", n => { NotAfter = n.GetDateTimeOffsetValue(); } },
                { "notBefore", n => { NotBefore = n.GetDateTimeOffsetValue(); } },
                { "robot", n => { Robot = n.GetObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.RobotSearchDto>(global::LGDXRobot2Cloud.UI.Client.Models.RobotSearchDto.CreateFromDiscriminatorValue); } },
                { "thumbprint", n => { Thumbprint = n.GetStringValue(); } },
                { "thumbprintBackup", n => { ThumbprintBackup = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("id", Id);
            writer.WriteDateTimeOffsetValue("notAfter", NotAfter);
            writer.WriteDateTimeOffsetValue("notBefore", NotBefore);
            writer.WriteObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.RobotSearchDto>("robot", Robot);
            writer.WriteStringValue("thumbprint", Thumbprint);
            writer.WriteStringValue("thumbprintBackup", ThumbprintBackup);
        }
    }
}
#pragma warning restore CS0618
