// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobot2Cloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RobotChassisInfoDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The batteryCount property</summary>
        public int? BatteryCount { get; set; }
        /// <summary>The batteryMaxVoltage property</summary>
        public double? BatteryMaxVoltage { get; set; }
        /// <summary>The batteryMinVoltage property</summary>
        public double? BatteryMinVoltage { get; set; }
        /// <summary>The chassisLengthX property</summary>
        public double? ChassisLengthX { get; set; }
        /// <summary>The chassisLengthY property</summary>
        public double? ChassisLengthY { get; set; }
        /// <summary>The chassisWheelCount property</summary>
        public int? ChassisWheelCount { get; set; }
        /// <summary>The chassisWheelRadius property</summary>
        public double? ChassisWheelRadius { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The robotTypeId property</summary>
        public int? RobotTypeId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobot2Cloud.UI.Client.Models.RobotChassisInfoDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobot2Cloud.UI.Client.Models.RobotChassisInfoDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobot2Cloud.UI.Client.Models.RobotChassisInfoDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batteryCount", n => { BatteryCount = n.GetIntValue(); } },
                { "batteryMaxVoltage", n => { BatteryMaxVoltage = n.GetDoubleValue(); } },
                { "batteryMinVoltage", n => { BatteryMinVoltage = n.GetDoubleValue(); } },
                { "chassisLengthX", n => { ChassisLengthX = n.GetDoubleValue(); } },
                { "chassisLengthY", n => { ChassisLengthY = n.GetDoubleValue(); } },
                { "chassisWheelCount", n => { ChassisWheelCount = n.GetIntValue(); } },
                { "chassisWheelRadius", n => { ChassisWheelRadius = n.GetDoubleValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "robotTypeId", n => { RobotTypeId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("batteryCount", BatteryCount);
            writer.WriteDoubleValue("batteryMaxVoltage", BatteryMaxVoltage);
            writer.WriteDoubleValue("batteryMinVoltage", BatteryMinVoltage);
            writer.WriteDoubleValue("chassisLengthX", ChassisLengthX);
            writer.WriteDoubleValue("chassisLengthY", ChassisLengthY);
            writer.WriteIntValue("chassisWheelCount", ChassisWheelCount);
            writer.WriteDoubleValue("chassisWheelRadius", ChassisWheelRadius);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("robotTypeId", RobotTypeId);
        }
    }
}
#pragma warning restore CS0618
