// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobot2Cloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RobotDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The assignedTasks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::LGDXRobot2Cloud.UI.Client.Models.AutoTaskListDto>? AssignedTasks { get; set; }
#nullable restore
#else
        public List<global::LGDXRobot2Cloud.UI.Client.Models.AutoTaskListDto> AssignedTasks { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The isProtectingHardwareSerialNumber property</summary>
        public bool? IsProtectingHardwareSerialNumber { get; set; }
        /// <summary>The isRealtimeExchange property</summary>
        public bool? IsRealtimeExchange { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The realm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobot2Cloud.UI.Client.Models.RealmSearchDto? Realm { get; set; }
#nullable restore
#else
        public global::LGDXRobot2Cloud.UI.Client.Models.RealmSearchDto Realm { get; set; }
#endif
        /// <summary>The robotCertificate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobot2Cloud.UI.Client.Models.RobotCertificateDto? RobotCertificate { get; set; }
#nullable restore
#else
        public global::LGDXRobot2Cloud.UI.Client.Models.RobotCertificateDto RobotCertificate { get; set; }
#endif
        /// <summary>The robotChassisInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobot2Cloud.UI.Client.Models.RobotChassisInfoDto? RobotChassisInfo { get; set; }
#nullable restore
#else
        public global::LGDXRobot2Cloud.UI.Client.Models.RobotChassisInfoDto RobotChassisInfo { get; set; }
#endif
        /// <summary>The robotSystemInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobot2Cloud.UI.Client.Models.RobotSystemInfoDto? RobotSystemInfo { get; set; }
#nullable restore
#else
        public global::LGDXRobot2Cloud.UI.Client.Models.RobotSystemInfoDto RobotSystemInfo { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobot2Cloud.UI.Client.Models.RobotDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobot2Cloud.UI.Client.Models.RobotDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobot2Cloud.UI.Client.Models.RobotDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignedTasks", n => { AssignedTasks = n.GetCollectionOfObjectValues<global::LGDXRobot2Cloud.UI.Client.Models.AutoTaskListDto>(global::LGDXRobot2Cloud.UI.Client.Models.AutoTaskListDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isProtectingHardwareSerialNumber", n => { IsProtectingHardwareSerialNumber = n.GetBoolValue(); } },
                { "isRealtimeExchange", n => { IsRealtimeExchange = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "realm", n => { Realm = n.GetObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.RealmSearchDto>(global::LGDXRobot2Cloud.UI.Client.Models.RealmSearchDto.CreateFromDiscriminatorValue); } },
                { "robotCertificate", n => { RobotCertificate = n.GetObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.RobotCertificateDto>(global::LGDXRobot2Cloud.UI.Client.Models.RobotCertificateDto.CreateFromDiscriminatorValue); } },
                { "robotChassisInfo", n => { RobotChassisInfo = n.GetObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.RobotChassisInfoDto>(global::LGDXRobot2Cloud.UI.Client.Models.RobotChassisInfoDto.CreateFromDiscriminatorValue); } },
                { "robotSystemInfo", n => { RobotSystemInfo = n.GetObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.RobotSystemInfoDto>(global::LGDXRobot2Cloud.UI.Client.Models.RobotSystemInfoDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::LGDXRobot2Cloud.UI.Client.Models.AutoTaskListDto>("assignedTasks", AssignedTasks);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("isProtectingHardwareSerialNumber", IsProtectingHardwareSerialNumber);
            writer.WriteBoolValue("isRealtimeExchange", IsRealtimeExchange);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.RealmSearchDto>("realm", Realm);
            writer.WriteObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.RobotCertificateDto>("robotCertificate", RobotCertificate);
            writer.WriteObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.RobotChassisInfoDto>("robotChassisInfo", RobotChassisInfo);
            writer.WriteObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.RobotSystemInfoDto>("robotSystemInfo", RobotSystemInfo);
        }
    }
}
#pragma warning restore CS0618
