// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobot2Cloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RobotSystemInfoDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The cpu property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cpu { get; set; }
#nullable restore
#else
        public string Cpu { get; set; }
#endif
        /// <summary>The gpu property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gpu { get; set; }
#nullable restore
#else
        public string Gpu { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The is32Bit property</summary>
        public bool? Is32Bit { get; set; }
        /// <summary>The isLittleEndian property</summary>
        public bool? IsLittleEndian { get; set; }
        /// <summary>The mcuSerialNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? McuSerialNumber { get; set; }
#nullable restore
#else
        public string McuSerialNumber { get; set; }
#endif
        /// <summary>The motherboard property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Motherboard { get; set; }
#nullable restore
#else
        public string Motherboard { get; set; }
#endif
        /// <summary>The motherboardSerialNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MotherboardSerialNumber { get; set; }
#nullable restore
#else
        public string MotherboardSerialNumber { get; set; }
#endif
        /// <summary>The os property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Os { get; set; }
#nullable restore
#else
        public string Os { get; set; }
#endif
        /// <summary>The ramMiB property</summary>
        public int? RamMiB { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobot2Cloud.UI.Client.Models.RobotSystemInfoDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobot2Cloud.UI.Client.Models.RobotSystemInfoDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobot2Cloud.UI.Client.Models.RobotSystemInfoDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cpu", n => { Cpu = n.GetStringValue(); } },
                { "gpu", n => { Gpu = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "is32Bit", n => { Is32Bit = n.GetBoolValue(); } },
                { "isLittleEndian", n => { IsLittleEndian = n.GetBoolValue(); } },
                { "mcuSerialNumber", n => { McuSerialNumber = n.GetStringValue(); } },
                { "motherboard", n => { Motherboard = n.GetStringValue(); } },
                { "motherboardSerialNumber", n => { MotherboardSerialNumber = n.GetStringValue(); } },
                { "os", n => { Os = n.GetStringValue(); } },
                { "ramMiB", n => { RamMiB = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cpu", Cpu);
            writer.WriteStringValue("gpu", Gpu);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("is32Bit", Is32Bit);
            writer.WriteBoolValue("isLittleEndian", IsLittleEndian);
            writer.WriteStringValue("mcuSerialNumber", McuSerialNumber);
            writer.WriteStringValue("motherboard", Motherboard);
            writer.WriteStringValue("motherboardSerialNumber", MotherboardSerialNumber);
            writer.WriteStringValue("os", Os);
            writer.WriteIntValue("ramMiB", RamMiB);
        }
    }
}
#pragma warning restore CS0618
