// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobot2Cloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TriggerRetryListDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The autoTask property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobot2Cloud.UI.Client.Models.AutoTaskSearchDto? AutoTask { get; set; }
#nullable restore
#else
        public global::LGDXRobot2Cloud.UI.Client.Models.AutoTaskSearchDto AutoTask { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The trigger property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobot2Cloud.UI.Client.Models.TriggerSearchDto? Trigger { get; set; }
#nullable restore
#else
        public global::LGDXRobot2Cloud.UI.Client.Models.TriggerSearchDto Trigger { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobot2Cloud.UI.Client.Models.TriggerRetryListDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobot2Cloud.UI.Client.Models.TriggerRetryListDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobot2Cloud.UI.Client.Models.TriggerRetryListDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoTask", n => { AutoTask = n.GetObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.AutoTaskSearchDto>(global::LGDXRobot2Cloud.UI.Client.Models.AutoTaskSearchDto.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "trigger", n => { Trigger = n.GetObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.TriggerSearchDto>(global::LGDXRobot2Cloud.UI.Client.Models.TriggerSearchDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.AutoTaskSearchDto>("autoTask", AutoTask);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteIntValue("id", Id);
            writer.WriteObjectValue<global::LGDXRobot2Cloud.UI.Client.Models.TriggerSearchDto>("trigger", Trigger);
        }
    }
}
#pragma warning restore CS0618
