// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobotCloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AutoTaskStatisticsDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The abortedTasks property</summary>
        public int? AbortedTasks { get; set; }
        /// <summary>The abortedTasksTrend property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? AbortedTasksTrend { get; set; }
#nullable restore
#else
        public List<int?> AbortedTasksTrend { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The completedTasks property</summary>
        public int? CompletedTasks { get; set; }
        /// <summary>The completedTasksTrend property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? CompletedTasksTrend { get; set; }
#nullable restore
#else
        public List<int?> CompletedTasksTrend { get; set; }
#endif
        /// <summary>The lastUpdatedAt property</summary>
        public DateTimeOffset? LastUpdatedAt { get; set; }
        /// <summary>The runningTasks property</summary>
        public int? RunningTasks { get; set; }
        /// <summary>The runningTasksTrend property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? RunningTasksTrend { get; set; }
#nullable restore
#else
        public List<int?> RunningTasksTrend { get; set; }
#endif
        /// <summary>The waitingTasks property</summary>
        public int? WaitingTasks { get; set; }
        /// <summary>The waitingTasksTrend property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? WaitingTasksTrend { get; set; }
#nullable restore
#else
        public List<int?> WaitingTasksTrend { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Models.AutoTaskStatisticsDto"/> and sets the default values.
        /// </summary>
        public AutoTaskStatisticsDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Models.AutoTaskStatisticsDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobotCloud.UI.Client.Models.AutoTaskStatisticsDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobotCloud.UI.Client.Models.AutoTaskStatisticsDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "abortedTasks", n => { AbortedTasks = n.GetIntValue(); } },
                { "abortedTasksTrend", n => { AbortedTasksTrend = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "completedTasks", n => { CompletedTasks = n.GetIntValue(); } },
                { "completedTasksTrend", n => { CompletedTasksTrend = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "lastUpdatedAt", n => { LastUpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "runningTasks", n => { RunningTasks = n.GetIntValue(); } },
                { "runningTasksTrend", n => { RunningTasksTrend = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "waitingTasks", n => { WaitingTasks = n.GetIntValue(); } },
                { "waitingTasksTrend", n => { WaitingTasksTrend = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("abortedTasks", AbortedTasks);
            writer.WriteCollectionOfPrimitiveValues<int?>("abortedTasksTrend", AbortedTasksTrend);
            writer.WriteIntValue("completedTasks", CompletedTasks);
            writer.WriteCollectionOfPrimitiveValues<int?>("completedTasksTrend", CompletedTasksTrend);
            writer.WriteDateTimeOffsetValue("lastUpdatedAt", LastUpdatedAt);
            writer.WriteIntValue("runningTasks", RunningTasks);
            writer.WriteCollectionOfPrimitiveValues<int?>("runningTasksTrend", RunningTasksTrend);
            writer.WriteIntValue("waitingTasks", WaitingTasks);
            writer.WriteCollectionOfPrimitiveValues<int?>("waitingTasksTrend", WaitingTasksTrend);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
