// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobotCloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AutoTaskDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assignedRobot property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobotCloud.UI.Client.Models.RobotSearchDto2? AssignedRobot { get; set; }
#nullable restore
#else
        public global::LGDXRobotCloud.UI.Client.Models.RobotSearchDto2 AssignedRobot { get; set; }
#endif
        /// <summary>The autoTaskDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::LGDXRobotCloud.UI.Client.Models.AutoTaskDetailDto>? AutoTaskDetails { get; set; }
#nullable restore
#else
        public List<global::LGDXRobotCloud.UI.Client.Models.AutoTaskDetailDto> AutoTaskDetails { get; set; }
#endif
        /// <summary>The currentProgress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobotCloud.UI.Client.Models.ProgressSearchDto? CurrentProgress { get; set; }
#nullable restore
#else
        public global::LGDXRobotCloud.UI.Client.Models.ProgressSearchDto CurrentProgress { get; set; }
#endif
        /// <summary>The flow property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobotCloud.UI.Client.Models.FlowSearchDto? Flow { get; set; }
#nullable restore
#else
        public global::LGDXRobotCloud.UI.Client.Models.FlowSearchDto Flow { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The priority property</summary>
        public int? Priority { get; set; }
        /// <summary>The realm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobotCloud.UI.Client.Models.RealmSearchDto? Realm { get; set; }
#nullable restore
#else
        public global::LGDXRobotCloud.UI.Client.Models.RealmSearchDto Realm { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Models.AutoTaskDto"/> and sets the default values.
        /// </summary>
        public AutoTaskDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Models.AutoTaskDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobotCloud.UI.Client.Models.AutoTaskDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobotCloud.UI.Client.Models.AutoTaskDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignedRobot", n => { AssignedRobot = n.GetObjectValue<global::LGDXRobotCloud.UI.Client.Models.RobotSearchDto2>(global::LGDXRobotCloud.UI.Client.Models.RobotSearchDto2.CreateFromDiscriminatorValue); } },
                { "autoTaskDetails", n => { AutoTaskDetails = n.GetCollectionOfObjectValues<global::LGDXRobotCloud.UI.Client.Models.AutoTaskDetailDto>(global::LGDXRobotCloud.UI.Client.Models.AutoTaskDetailDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "currentProgress", n => { CurrentProgress = n.GetObjectValue<global::LGDXRobotCloud.UI.Client.Models.ProgressSearchDto>(global::LGDXRobotCloud.UI.Client.Models.ProgressSearchDto.CreateFromDiscriminatorValue); } },
                { "flow", n => { Flow = n.GetObjectValue<global::LGDXRobotCloud.UI.Client.Models.FlowSearchDto>(global::LGDXRobotCloud.UI.Client.Models.FlowSearchDto.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "realm", n => { Realm = n.GetObjectValue<global::LGDXRobotCloud.UI.Client.Models.RealmSearchDto>(global::LGDXRobotCloud.UI.Client.Models.RealmSearchDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::LGDXRobotCloud.UI.Client.Models.RobotSearchDto2>("assignedRobot", AssignedRobot);
            writer.WriteCollectionOfObjectValues<global::LGDXRobotCloud.UI.Client.Models.AutoTaskDetailDto>("autoTaskDetails", AutoTaskDetails);
            writer.WriteObjectValue<global::LGDXRobotCloud.UI.Client.Models.ProgressSearchDto>("currentProgress", CurrentProgress);
            writer.WriteObjectValue<global::LGDXRobotCloud.UI.Client.Models.FlowSearchDto>("flow", Flow);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("priority", Priority);
            writer.WriteObjectValue<global::LGDXRobotCloud.UI.Client.Models.RealmSearchDto>("realm", Realm);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
