// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobotCloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlowDetailUpdateDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The autoTaskNextControllerId property</summary>
        public int? AutoTaskNextControllerId { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The order property</summary>
        public int? Order { get; set; }
        /// <summary>The progressId property</summary>
        public int? ProgressId { get; set; }
        /// <summary>The triggerId property</summary>
        public int? TriggerId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Models.FlowDetailUpdateDto"/> and sets the default values.
        /// </summary>
        public FlowDetailUpdateDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Models.FlowDetailUpdateDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobotCloud.UI.Client.Models.FlowDetailUpdateDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobotCloud.UI.Client.Models.FlowDetailUpdateDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoTaskNextControllerId", n => { AutoTaskNextControllerId = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "order", n => { Order = n.GetIntValue(); } },
                { "progressId", n => { ProgressId = n.GetIntValue(); } },
                { "triggerId", n => { TriggerId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("autoTaskNextControllerId", AutoTaskNextControllerId);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("order", Order);
            writer.WriteIntValue("progressId", ProgressId);
            writer.WriteIntValue("triggerId", TriggerId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
