// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobotCloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RobotCertificateIssueDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The robot property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobotCloud.UI.Client.Models.RobotSearchDto? Robot { get; set; }
#nullable restore
#else
        public global::LGDXRobotCloud.UI.Client.Models.RobotSearchDto Robot { get; set; }
#endif
        /// <summary>The robotCertificatePrivateKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RobotCertificatePrivateKey { get; set; }
#nullable restore
#else
        public string RobotCertificatePrivateKey { get; set; }
#endif
        /// <summary>The robotCertificatePublicKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RobotCertificatePublicKey { get; set; }
#nullable restore
#else
        public string RobotCertificatePublicKey { get; set; }
#endif
        /// <summary>The rootCertificate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RootCertificate { get; set; }
#nullable restore
#else
        public string RootCertificate { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Models.RobotCertificateIssueDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobotCloud.UI.Client.Models.RobotCertificateIssueDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobotCloud.UI.Client.Models.RobotCertificateIssueDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "robot", n => { Robot = n.GetObjectValue<global::LGDXRobotCloud.UI.Client.Models.RobotSearchDto>(global::LGDXRobotCloud.UI.Client.Models.RobotSearchDto.CreateFromDiscriminatorValue); } },
                { "robotCertificatePrivateKey", n => { RobotCertificatePrivateKey = n.GetStringValue(); } },
                { "robotCertificatePublicKey", n => { RobotCertificatePublicKey = n.GetStringValue(); } },
                { "rootCertificate", n => { RootCertificate = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::LGDXRobotCloud.UI.Client.Models.RobotSearchDto>("robot", Robot);
            writer.WriteStringValue("robotCertificatePrivateKey", RobotCertificatePrivateKey);
            writer.WriteStringValue("robotCertificatePublicKey", RobotCertificatePublicKey);
            writer.WriteStringValue("rootCertificate", RootCertificate);
        }
    }
}
#pragma warning restore CS0618
