// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobotCloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WaypointDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The hasCharger property</summary>
        public bool? HasCharger { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The isParking property</summary>
        public bool? IsParking { get; set; }
        /// <summary>The isReserved property</summary>
        public bool? IsReserved { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The realm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobotCloud.UI.Client.Models.RealmSearchDto? Realm { get; set; }
#nullable restore
#else
        public global::LGDXRobotCloud.UI.Client.Models.RealmSearchDto Realm { get; set; }
#endif
        /// <summary>The rotation property</summary>
        public double? Rotation { get; set; }
        /// <summary>The x property</summary>
        public double? X { get; set; }
        /// <summary>The y property</summary>
        public double? Y { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Models.WaypointDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobotCloud.UI.Client.Models.WaypointDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobotCloud.UI.Client.Models.WaypointDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "hasCharger", n => { HasCharger = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "isParking", n => { IsParking = n.GetBoolValue(); } },
                { "isReserved", n => { IsReserved = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "realm", n => { Realm = n.GetObjectValue<global::LGDXRobotCloud.UI.Client.Models.RealmSearchDto>(global::LGDXRobotCloud.UI.Client.Models.RealmSearchDto.CreateFromDiscriminatorValue); } },
                { "rotation", n => { Rotation = n.GetDoubleValue(); } },
                { "x", n => { X = n.GetDoubleValue(); } },
                { "y", n => { Y = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("hasCharger", HasCharger);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("isParking", IsParking);
            writer.WriteBoolValue("isReserved", IsReserved);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::LGDXRobotCloud.UI.Client.Models.RealmSearchDto>("realm", Realm);
            writer.WriteDoubleValue("rotation", Rotation);
            writer.WriteDoubleValue("x", X);
            writer.WriteDoubleValue("y", Y);
        }
    }
}
#pragma warning restore CS0618
