// <auto-generated/>
#pragma warning disable CS0618
using LGDXRobot2Cloud.UI.Client.Administration.ApiKeys;
using LGDXRobot2Cloud.UI.Client.Administration.RobotCertificates;
using LGDXRobot2Cloud.UI.Client.Administration.Roles;
using LGDXRobot2Cloud.UI.Client.Administration.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LGDXRobot2Cloud.UI.Client.Administration
{
    /// <summary>
    /// Builds and executes requests for operations under \Administration
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdministrationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ApiKeys property</summary>
        public global::LGDXRobot2Cloud.UI.Client.Administration.ApiKeys.ApiKeysRequestBuilder ApiKeys
        {
            get => new global::LGDXRobot2Cloud.UI.Client.Administration.ApiKeys.ApiKeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RobotCertificates property</summary>
        public global::LGDXRobot2Cloud.UI.Client.Administration.RobotCertificates.RobotCertificatesRequestBuilder RobotCertificates
        {
            get => new global::LGDXRobot2Cloud.UI.Client.Administration.RobotCertificates.RobotCertificatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Roles property</summary>
        public global::LGDXRobot2Cloud.UI.Client.Administration.Roles.RolesRequestBuilder Roles
        {
            get => new global::LGDXRobot2Cloud.UI.Client.Administration.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Users property</summary>
        public global::LGDXRobot2Cloud.UI.Client.Administration.Users.UsersRequestBuilder Users
        {
            get => new global::LGDXRobot2Cloud.UI.Client.Administration.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobot2Cloud.UI.Client.Administration.AdministrationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdministrationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Administration", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobot2Cloud.UI.Client.Administration.AdministrationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdministrationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Administration", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
