// <auto-generated/>
#pragma warning disable CS0618
using LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.Abort;
using LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.AbortGoal;
using LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.Complete;
using LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.EmergencyStop;
using LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.RefreshMap;
using LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.SaveMap;
using LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.SetGoal;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam
{
    /// <summary>
    /// Builds and executes requests for operations under \Navigation\Realms\{id}\Slam
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SlamRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Abort property</summary>
        public global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.Abort.AbortRequestBuilder Abort
        {
            get => new global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.Abort.AbortRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The AbortGoal property</summary>
        public global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.AbortGoal.AbortGoalRequestBuilder AbortGoal
        {
            get => new global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.AbortGoal.AbortGoalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Complete property</summary>
        public global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.Complete.CompleteRequestBuilder Complete
        {
            get => new global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.Complete.CompleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The EmergencyStop property</summary>
        public global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.EmergencyStop.EmergencyStopRequestBuilder EmergencyStop
        {
            get => new global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.EmergencyStop.EmergencyStopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RefreshMap property</summary>
        public global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.RefreshMap.RefreshMapRequestBuilder RefreshMap
        {
            get => new global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.RefreshMap.RefreshMapRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SaveMap property</summary>
        public global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.SaveMap.SaveMapRequestBuilder SaveMap
        {
            get => new global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.SaveMap.SaveMapRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SetGoal property</summary>
        public global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.SetGoal.SetGoalRequestBuilder SetGoal
        {
            get => new global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.SetGoal.SetGoalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.SlamRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SlamRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Navigation/Realms/{id}/Slam", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Navigation.Realms.Item.Slam.SlamRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SlamRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Navigation/Realms/{id}/Slam", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
