// <auto-generated/>
#pragma warning disable CS0618
using LGDXRobotCloud.UI.Client.Administration.ActivityLogs;
using LGDXRobotCloud.UI.Client.Administration.ApiKeys;
using LGDXRobotCloud.UI.Client.Administration.RobotCertificates;
using LGDXRobotCloud.UI.Client.Administration.Roles;
using LGDXRobotCloud.UI.Client.Administration.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LGDXRobotCloud.UI.Client.Administration
{
    /// <summary>
    /// Builds and executes requests for operations under \Administration
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdministrationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ActivityLogs property</summary>
        public global::LGDXRobotCloud.UI.Client.Administration.ActivityLogs.ActivityLogsRequestBuilder ActivityLogs
        {
            get => new global::LGDXRobotCloud.UI.Client.Administration.ActivityLogs.ActivityLogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ApiKeys property</summary>
        public global::LGDXRobotCloud.UI.Client.Administration.ApiKeys.ApiKeysRequestBuilder ApiKeys
        {
            get => new global::LGDXRobotCloud.UI.Client.Administration.ApiKeys.ApiKeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RobotCertificates property</summary>
        public global::LGDXRobotCloud.UI.Client.Administration.RobotCertificates.RobotCertificatesRequestBuilder RobotCertificates
        {
            get => new global::LGDXRobotCloud.UI.Client.Administration.RobotCertificates.RobotCertificatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Roles property</summary>
        public global::LGDXRobotCloud.UI.Client.Administration.Roles.RolesRequestBuilder Roles
        {
            get => new global::LGDXRobotCloud.UI.Client.Administration.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Users property</summary>
        public global::LGDXRobotCloud.UI.Client.Administration.Users.UsersRequestBuilder Users
        {
            get => new global::LGDXRobotCloud.UI.Client.Administration.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Administration.AdministrationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdministrationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Administration", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Administration.AdministrationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdministrationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Administration", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
