// <auto-generated/>
#pragma warning disable CS0618
using LGDXRobotCloud.UI.Client.Administration;
using LGDXRobotCloud.UI.Client.Automation;
using LGDXRobotCloud.UI.Client.Identity;
using LGDXRobotCloud.UI.Client.Navigation;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LGDXRobotCloud.UI.Client
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LgdxApiClient : BaseRequestBuilder
    {
        /// <summary>The Administration property</summary>
        public global::LGDXRobotCloud.UI.Client.Administration.AdministrationRequestBuilder Administration
        {
            get => new global::LGDXRobotCloud.UI.Client.Administration.AdministrationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Automation property</summary>
        public global::LGDXRobotCloud.UI.Client.Automation.AutomationRequestBuilder Automation
        {
            get => new global::LGDXRobotCloud.UI.Client.Automation.AutomationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Identity property</summary>
        public global::LGDXRobotCloud.UI.Client.Identity.IdentityRequestBuilder Identity
        {
            get => new global::LGDXRobotCloud.UI.Client.Identity.IdentityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Navigation property</summary>
        public global::LGDXRobotCloud.UI.Client.Navigation.NavigationRequestBuilder Navigation
        {
            get => new global::LGDXRobotCloud.UI.Client.Navigation.NavigationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.LgdxApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LgdxApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
